
const loginForm = document.querySelector("#login-form");
const registerForm = document.querySelector("#register-form");
const showRegisterLink = document.querySelector("#show-register");
const showLoginLink = document.querySelector("#show-login");

showRegisterLink.addEventListener("click", (e) => {
  e.preventDefault();
  loginForm.style.display = "none";
  registerForm.style.display = "block";
});

showLoginLink.addEventListener("click", (e) => {
  e.preventDefault();
  registerForm.style.display = "none";
  loginForm.style.display = "block";
});


const togglePasswordLogin = document.querySelector("#login-eye");
const passwordInputLogin = document.querySelector("#login-pass");

togglePasswordLogin.addEventListener("click", () => {
  const type =
    passwordInputLogin.getAttribute("type") === "password"
      ? "text"
      : "password";
  passwordInputLogin.setAttribute("type", type);
  togglePasswordLogin.classList.toggle("ri-eye-off-line");
  togglePasswordLogin.classList.toggle("ri-eye-line");
});

// Xử lý mắt xem mật khẩu (form register)
const togglePasswordRegister = document.querySelector("#register-eye-pass");
const passwordInputRegister = document.querySelector("#register-pass");

togglePasswordRegister.addEventListener("click", () => {
  const type =
    passwordInputRegister.getAttribute("type") === "password"
      ? "text"
      : "password";
  passwordInputRegister.setAttribute("type", type);
  togglePasswordRegister.classList.toggle("ri-eye-off-line");
  togglePasswordRegister.classList.toggle("ri-eye-line");
});

// Xử lý mắt xem nhập lại mật khẩu (form register)
const toggleConfirmPassword = document.querySelector("#register-eye-confirm");
const confirmPasswordInput = document.querySelector("#register-confirm-pass");

toggleConfirmPassword.addEventListener("click", () => {
  const type =
    confirmPasswordInput.getAttribute("type") === "password"
      ? "text"
      : "password";
  confirmPasswordInput.setAttribute("type", type);
  toggleConfirmPassword.classList.toggle("ri-eye-off-line");
  toggleConfirmPassword.classList.toggle("ri-eye-line");
});

// Xử lý cập nhật quận/huyện dựa trên tỉnh/thành
const provinceSelect = document.querySelector("#register-province");
const districtSelect = document.querySelector("#register-district");

const districts = {
  "Hà Nội": [
    "Ba Đình","Hoàn Kiếm",
    "Đống Đa",
    "Hai Bà Trưng",
    "Thanh Xuân",
    "Cầu Giấy",
    "Hoàng Mai",
    "Long Biên",
    "Tây Hồ",
    "Bắc Từ Liêm",
    "Nam Từ Liêm",
    "Hà Đông",
    "Sơn Tây",
    "Đông Anh",
    "Gia Lâm",
    "Thanh Trì",
    "Thường Tín",
    "Thanh Oai",
    "Mê Linh",
  ],
  "TP Hồ Chí Minh": [
    "Quận 1",
    "Quận 3",
    "Quận 4",
    "Quận 5",
    "Quận 6",
    "Quận 7",
    "Quận 8",
    "Quận 10",
    "Quận 11",
    "Quận 12",
    "Bình Thạnh",
    "Gò Vấp",
    "Phú Nhuận",
    "Tân Bình",
    "Tân Phú",
    "Thủ Đức",
    "Bình Tân",
    "Cần Giờ",
    "Củ Chi",
    "Hóc Môn",
    "Nhà Bè",
  ],
  "Đà Nẵng": [
    "Hải Châu",
    "Thanh Khê",
    "Sơn Trà",
    "Ngũ Hành Sơn",
    "Liên Chiểu",
    "Cẩm Lệ",
    "Hòa Vang",
    "Hoàng Sa",
  ],
  "Hải Phòng": [
    "Hồng Bàng",
    "Ngô Quyền",
    "Lê Chân",
    "Hải An",
    "Kiến An",
    "Đồ Sơn",
    "Dương Kinh",
    "Thủy Nguyên",
    "An Dương",
    "An Lão",
    "Kiến Thụy",
    "Tiên Lãng",
    "Vĩnh Bảo",
    "Cát Hải",
  ],
  "Cần Thơ": [
    "Ninh Kiều",
    "Bình Thủy",
    "Cái Răng",
    "Thốt Nốt",
    "Ô Môn",
    "Phong Điền",
    "Cờ Đỏ",
    "Thới Lai",
    "Vĩnh Thạnh",
  ],
  "An Giang": [
    "Long Xuyên",
    "Châu Đốc",
    "Châu Phú",
    "Tân Châu",
    "Châu Thành",
    "An Phú",
    "Thoại Sơn",
    "Chợ Mới",
    "Tri Tôn",
    "Tịnh Biên",
  ],
  "Bà Rịa - Vũng Tàu": [
    "Vũng Tàu",
    "Bà Rịa",
    "Châu Đức",
    "Xuyên Mộc",
    "Long Điền",
    "Đất Đỏ",
    "Tân Thành",
    "Côn Đảo",
  ],
  "Bắc Giang": [
    "Yên Dũng",
    "Việt Yên",
    "Tân Yên",
    "Lục Nam",
    "Lục Ngạn",
    "Sơn Động",
    "Lạng Giang",
    "Hiệp Hòa",
  ],
  "Bắc Kạn": ["Ba Bể", "Bạch Thông", "Chợ Đồn", "Chợ Mới", "Na Rì", "Ngân Sơn"],
  "Bạc Liêu": ["Hồng Dân", "Phước Long", "Vĩnh Lợi", "Đông Hải", "Giá Rai"],
  "Bắc Ninh": [
    "Yên Phong",
    "Tiên Du",
    "Quế Võ",
    "Lương Tài",
    "Thuận Thành",
    "Từ Sơn",
    "Gia Bình",
  ],
  "Bến Tre": [
    "Châu Thành",
    "Chợ Lách",
    "Mỏ Cày Bắc",
    "Mỏ Cày Nam",
    "Giồng Trôm",
    "Bình Đại",
    "Ba Tri",
    "Thạnh Phú",
  ],
  "Bình Định": [
    "An Lão",
    "Hoài Ân",
    "Hoài Nhơn",
    "Phù Mỹ",
    "Phù Cát",
    "Tây Sơn",
    "Vân Canh",
    "An Nhơn",
    "Tuy Phước",
  ],
  "Bình Dương": [
    "Bến Cát",
    "Dầu Tiếng",
    "Dĩ An",
    "Phú Giáo",
    "Tân Uyên",
    "Thuận An",
  ],
  "Bình Phước": [
    "Bù Đăng",
    "Bù Đốp",
    "Bù Gia Mập",
    "Chơn Thành",
    "Đồng Phú",
    "Hớn Quản",
    "Lộc Ninh",
    "Phú Riềng",
  ],
  "Bình Thuận": [
    "Bắc Bình",
    "Đồng Xuân",
    "Hàm Thuận Bắc",
    "Hàm Thuận Nam",
    "Phú Quý",
    "Tánh Linh",
    "Tuy Phong",
    "Hàm Tân",
  ],
  "Cà Mau": [
    "Cái Nước",
    "Đầm Dơi",
    "Năm Căn",
    "Ngọc Hiển",
    "Phú Tân",
    "Thới Bình",
    "Trần Văn Thời",
    "U Minh",
  ],
  "Cao Bằng": [
    "Bảo Lạc",
    "Bảo Lâm",
    "Hà Quảng",
    "Hạ Lang",
    "Nguyên Bình",
    "Phục Hòa",
    "Quảng Uyên",
    "Thạch An",
    "Trùng Khánh",
  ],
  "Đắk Lắk": [
    "Buôn Đôn",
    "Cư Kuin",
    "Cư M'gar",
    "Ea H'leo",
    "Ea Kar",
    "Ea Súp",
    "Krông Ana",
    "Krông Bông",
    "Krông Năng",
    "Krông Pắc",
    "Lắk",
    "M'Đrăk",
  ],
  "Đắk Nông": [
    "Cư Jút",
    "Đắk Glong",
    "Đắk Mil",
    "Đắk R'Lấp",
    "Đắk Song",
    "Krông Nô",
    "Tuy Đức",
  ],
  "Điện Biên": [
    "Điện Biên Đông",
    "Mường Ảng",
    "Mường Chà",
    "Mường Lay",
    "Mường Nhé",
    "Nậm Pồ",
    "Tủa Chùa",
    "Tuần Giáo",
  ],
  "Đồng Nai": [
    "Cẩm Mỹ",
    "Định Quán",
    "Long Thành",
    "Nhơn Trạch",
    "Tân Phú",
    "Thống Nhất",
    "Trảng Bom",
    "Vĩnh Cửu",
    "Xuân Lộc",
  ],
  "Đồng Tháp": [
    "Cao Lãnh",
    "Châu Thành",
    "Hồng Ngự",
    "Lai Vung",
    "Tam Nông",
    "Tân Hồng",
    "Thanh Bình",
    "Tháp Mười",
  ],
  "Gia Lai": [
    "Chư Păh",
    "Chư Prông",
    "Chư Sê",
    "Đak Đoa",
    "Đak Pơ",
    "Ia Grai",
    "Ia Pa",
    "Kbang",
    "Kông Chro",
    "Krông Pa",
    "Mang Yang",
  ],
  "Hà Giang": [
    "Bắc Mê",
    "Bắc Quang",
    "Đồng Văn",
    "Hoàng Su Phì",
    "Mèo Vạc",
    "Quản Bạ",
    "Vị Xuyên",
    "Xín Mần",
    "Yên Minh",
  ],
  "Hà Nam": ["Bình Lục", "Duy Tiên", "Kim Bảng", "Lý Nhân", "Thanh Liêm"],
  "Hà Tĩnh": [
    "Cẩm Xuyên",
    "Can Lộc",
    "Đức Thọ",
    "Hương Khê",
    "Hương Sơn",
    "Kỳ Anh",
    "Lộc Hà",
    "Nghi Xuân",
    "Thạch Hà",
    "Vũ Quang",
  ],
  "Hải Dương": [
    "Bình Giang",
    "Cẩm Giàng",
    "Chí Linh",
    "Gia Lộc",
    "Kim Thành",
    "Kinh Môn",
    "Nam Sách",
    "Ninh Giang",
    "Tứ Kỳ",
    "Thanh Hà",
    "Thanh Miện",
  ],
  "Hậu Giang": [
    "Châu Thành",
    "Châu Thành A",
    "Long Mỹ",
    "Phụng Hiệp",
    "Vị Thủy",
  ],
  "Hòa Bình": [
    "Cao Phong",
    "Đà Bắc",
    "Kỳ Sơn",
    "Lạc Sơn",
    "Lạc Thủy",
    "Mai Châu",
    "Tân Lạc",
    "Yên Thủy",
  ],
  "Hưng Yên": [
    "Ân Thi",
    "Khoái Châu",
    "Kim Động",
    "Mỹ Hào",
    "Phù Cừ",
    "Tiên Lữ",
    "Văn Giang",
    "Văn Lâm",
    "Yên Mỹ",
  ],
  "Khánh Hòa": [
    "Cam Lâm",
    "Cam Ranh",
    "Diên Khánh",
    "Khánh Sơn",
    "Khánh Vĩnh",
    "Ninh Hòa",
    "Trường Sa",
    "Vạn Ninh",
  ],
  "Kiên Giang": [
    "Châu Thành",
    "Giang Thành",
    "Gò Quao",
    "Hà Tiên",
    "Hòn Đất",
    "Kiên Hải",
    "Phú Quốc",
    "Rạch Giá",
    "Tân Hiệp",
    "U Minh Thượng",
    "Vĩnh Thuận",
  ],
  "Kon Tum": [
    "Đắk Glei",
    "Đắk Hà",
    "Đắk Tô",
    "Kon Plông",
    "Kon Rẫy",
    "Ngọc Hồi",
    "Sa Thầy",
    "Tu Mơ Rông",
  ],
  "Lai Châu": [
    "Mường Tè",
    "Nậm Nhùn",
    "Phong Thổ",
    "Sìn Hồ",
    "Tam Đường",
    "Than Uyên",
  ],
  "Lâm Đồng": [
    "Bảo Lâm",
    "Cát Tiên",
    "Đà Lạt",
    "Đam Rông",
    "Di Linh",
    "Đơn Dương",
    "Đức Trọng",
    "Lạc Dương",
    "Lâm Hà",
  ],
  "Lạng Sơn": [
    "Bắc Sơn",
    "Bình Gia",
    "Cao Lộc",
    "Chi Lăng",
    "Đình Lập",
    "Hữu Lũng",
    "Lộc Bình",
    "Tràng Định",
    "Văn Lãng",
    "Văn Quan",
  ],
  "Lào Cai": [
    "Bảo Thắng",
    "Bảo Yên",
    "Bát Xát",
    "Mường Khương",
    "Sa Pa",
    "Si Ma Cai",
    "Văn Bàn",
  ],
  "Long An": [
    "Bến Lức",
    "Cần Đước",
    "Cần Giuộc",
    "Châu Thành",
    "Đức Hòa",
    "Đức Huệ",
    "Mộc Hóa",
    "Tân Hưng",
    "Tân Thạnh",
    "Tân Trụ",
    "Thạnh Hóa",
    "Thủ Thừa",
    "Vĩnh Hưng",
  ],
  "Nam Định": [
    "Giao Thủy",
    "Hải Hậu",
    "Mỹ Lộc",
    "Nam Trực",
    "Nghĩa Hưng",
    "Trực Ninh",
    "Vụ Bản",
    "Xuân Trường",
    "Ý Yên",
  ],
  "Nghệ An": [
    "Anh Sơn",
    "Con Cuông",
    "Diễn Châu",
    "Đô Lương",
    "Hưng Nguyên",
    "Kỳ Sơn",
    "Nam Đàn",
    "Nghi Lộc",
    "Quế Phong",
    "Quỳ Châu",
    "Quỳ Hợp",
    "Quỳnh Lưu",
    "Tân Kỳ",
    "Thanh Chương",
    "Tương Dương",
    "Yên Thành",
  ],
  "Ninh Bình": [
    "Gia Viễn",
    "Hoa Lư",
    "Kim Sơn",
    "Nho Quan",
    "Tam Điệp",
    "Yên Khánh",
    "Yên Mô",
  ],
  "Ninh Thuận": ["Bác Ái", "Ninh Hải", "Ninh Phước", "Thuận Bắc", "Thuận Nam"],
  "Phú Thọ": [
    "Cẩm Khê",
    "Đoan Hùng",
    "Hạ Hòa",
    "Lâm Thao",
    "Phù Ninh",
    "Tam Nông",
    "Thanh Ba",
    "Thanh Sơn",
    "Thanh Thủy",
    "Yên Lập",
  ],
  "Quảng Bình": [
    "Bố Trạch",
    "Lệ Thủy",
    "Minh Hóa",
    "Quảng Ninh",
    "Quảng Trạch",
    "Tuyên Hóa",
  ],
  "Quảng Nam": [
    "Đại Lộc",
    "Duy Xuyên",
    "Điện Bàn",
    "Hiệp Đức",
    "Nông Sơn",
    "Phú Ninh",
    "Quế Sơn",
    "Tiên Phước",
    "Thăng Bình",
    "Tây Giang",
    "Đông Giang",
    "Nam Giang",
    "Đại Lộc",
  ],
  "Quảng Ngãi": [
    "Ba Tơ",
    "Bình Sơn",
    "Đức Phổ",
    "Lý Sơn",
    "Minh Long",
    "Mộ Đức",
    "Nghĩa Hành",
    "Sơn Hà",
    "Sơn Tây",
    "Tây Trà",
    "Trà Bồng",
  ],
  "Quảng Ninh": [
    "Ba Chẽ",
    "Bình Liêu",
    "Đầm Hà",
    "Đông Triều",
    "Hạ Long",
    "Hải Hà",
    "Móng Cái",
    "Quảng Yên",
    "Tiên Yên",
    "Uông Bí",
    "Vân Đồn",
  ],
  "Quảng Trị": [
    "Cam Lộ",
    "Cồn Cỏ",
    "Đa Krông",
    "Gio Linh",
    "Hải Lăng",
    "Hướng Hóa",
    "Triệu Phong",
    "Vĩnh Linh",
  ],
  "Sóc Trăng": [
    "Châu Thành",
    "Cù Lao Dung",
    "Kế Sách",
    "Long Phú",
    "Mỹ Tú",
    "Mỹ Xuyên",
    "Ngã Năm",
    "Thạnh Trị",
    "Vĩnh Châu",
  ],
  "Sơn La": [
    "Mai Sơn",
    "Mộc Châu",
    "Phù Yên",
    "Quỳnh Nhai",
    "Sông Mã",
    "Sốp Cộp",
    "Thuận Châu",
    "Vân Hồ",
    "Yên Châu",
  ],
  "Tây Ninh": [
    "Bến Cầu",
    "Châu Thành",
    "Dương Minh Châu",
    "Gò Dầu",
    "Hòa Thành",
    "Trảng Bàng",
  ],
  "Thái Bình": [
    "Đông Hưng",
    "Hưng Hà",
    "Kiến Xương",
    "Quỳnh Phụ",
    "Thái Thụy",
    "Tiền Hải",
    "Vũ Thư",
  ],
  "Thái Nguyên": [
    "Định Hóa",
    "Đồng Hỷ",
    "Phú Bình",
    "Phú Lương",
    "Võ Nhai",
    "Đại Từ",
  ],
  "Thanh Hóa": [
    "Bá Thước",
    "Cẩm Thủy",
    "Đông Sơn",
    "Hà Trung",
    "Hoằng Hóa",
    "Lang Chánh",
    "Mường Lát",
    "Nga Sơn",
    "Như Thanh",
    "Như Xuân",
    "Nông Cống",
    "Quan Hóa",
    "Quan Sơn",
    "Quảng Xương",
    "Thạch Thành",
    "Thiệu Hóa",
    "Thọ Xuân",
    "Triệu Sơn",
    "Vĩnh Lộc",
    "Yên Định",
  ],
  "Thừa Thiên Huế": [
    "A Lưới",
    "Hương Thủy",
    "Hương Trà",
    "Nam Đông",
    "Phong Điền",
    "Phú Lộc",
    "Phú Vang",
    "Quảng Điền",
  ],
  "Tiền Giang": [
    "Cái Bè",
    "Cai Lậy",
    "Châu Thành",
    "Chợ Gạo",
    "Gò Công Đông",
    "Gò Công Tây",
    "Tân Phước",
  ],
  "Trà Vinh": [
    "Càng Long",
    "Cầu Kè",
    "Cầu Ngang",
    "Châu Thành",
    "Duyên Hải",
    "Tiểu Cần",
    "Trà Cú",
  ],
  "Tuyên Quang": [
    "Chiêm Hóa",
    "Hàm Yên",
    "Lâm Bình",
    "Na Hang",
    "Sơn Dương",
    "Yên Sơn",
  ],
  "Vĩnh Long": [
    "Bình Tân",
    "Long Hồ",
    "Mang Thít",
    "Tam Bình",
    "Trà Ôn",
    "Vũng Liêm",
  ],
  "Vĩnh Phúc": [
    "Bình Xuyên",
    "Lập Thạch",
    "Sông Lô",
    "Tam Đảo",
    "Tam Dương",
    "Vĩnh Tường",
    "Yên Lạc",
  ],
  "Yên Bái": [
    "Lục Yên",
    "Mù Cang Chải",
    "Trạm Tấu",
    "Trấn Yên",
    "Văn Chấn",
    "Văn Yên",
  ],
};

provinceSelect.addEventListener("change", () => {
  const selectedProvince = provinceSelect.value;
  districtSelect.innerHTML =
    '<option value="" disabled selected>Select District</option>';

  if (districts[selectedProvince]) {
    districts[selectedProvince].forEach((district) => {
      const option = document.createElement("option");
      option.value = district;
      option.textContent = district;
      districtSelect.appendChild(option);
    });
  }
});
